# Generated by Django 5.1 on 2024-09-02 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moncalc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horisontal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gu_height', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='headunit',
            name='width',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='moncalc.horisontal'),
        ),
    ]
