# Generated by Django 5.1 on 2024-09-02 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moncalc', '0002_horisontal_headunit_width'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Vertical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='horisontal',
            name='gu_height',
        ),
        migrations.AddField(
            model_name='headunit',
            name='gu_diag',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='moncalc.diagonal'),
        ),
        migrations.AddField(
            model_name='headunit',
            name='height',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='moncalc.vertical'),
        ),
    ]
