# Generated by Django 5.1 on 2024-09-03 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moncalc', '0003_diagonal_vertical_remove_horisontal_gu_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagonal',
            name='gu_diag',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AddField(
            model_name='horisontal',
            name='gu_width',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AddField(
            model_name='vertical',
            name='gu_height',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='headunit',
            name='gu_diag',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.DO_NOTHING, to='moncalc.diagonal'),
        ),
        migrations.AlterField(
            model_name='headunit',
            name='height',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.DO_NOTHING, to='moncalc.vertical'),
        ),
        migrations.AlterField(
            model_name='headunit',
            name='width',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.DO_NOTHING, to='moncalc.horisontal'),
        ),
    ]
