# Generated by Django 5.1 on 2024-09-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moncalc', '0006_alter_headunit_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='headunit',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='diagonal',
            name='gu_diag',
            field=models.DecimalField(decimal_places=5, default='0', max_digits=5, max_length=5, verbose_name='Диагональ'),
        ),
        migrations.AlterField(
            model_name='horisontal',
            name='gu_width',
            field=models.DecimalField(decimal_places=5, default='0', max_digits=5, max_length=5, verbose_name='Ширина'),
        ),
        migrations.AlterField(
            model_name='vertical',
            name='gu_height',
            field=models.DecimalField(decimal_places=5, default='0', max_digits=5, max_length=5, verbose_name='Высота'),
        ),
    ]
