# Generated by Django 5.1 on 2024-09-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moncalc', '0008_alter_headunit_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagonal',
            name='gu_diag',
            field=models.CharField(default='0', max_length=5, verbose_name='Диагональ'),
        ),
        migrations.AlterField(
            model_name='horisontal',
            name='gu_width',
            field=models.CharField(default='0', max_length=5, verbose_name='Ширина'),
        ),
        migrations.AlterField(
            model_name='vertical',
            name='gu_height',
            field=models.CharField(default='0', max_length=5, verbose_name='Высота'),
        ),
    ]
