# Generated by Django 5.1 on 2024-09-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moncalc', '0009_alter_diagonal_gu_diag_alter_horisontal_gu_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headunit',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
