# Generated by Django 5.1 on 2024-09-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moncalc', '0010_headunit_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='headunit',
            name='osys',
            field=models.CharField(default='Android', max_length=20, verbose_name='Операционная система'),
        ),
    ]
