# Generated by Django 5.1 on 2024-09-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moncalc', '0011_headunit_osys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headunit',
            name='gu_diag',
            field=models.CharField(default='0', max_length=5, verbose_name='Диагональ'),
        ),
        migrations.AlterField(
            model_name='headunit',
            name='height',
            field=models.CharField(default='0', max_length=5, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='headunit',
            name='width',
            field=models.CharField(default='0', max_length=5, verbose_name='Ширина'),
        ),
    ]
