# Generated by Django 5.1 on 2024-09-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moncalc', '0012_alter_headunit_gu_diag_alter_headunit_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headunit',
            name='gu_diag_int',
            field=models.IntegerField(default=0, verbose_name='Приближенная диагональ'),
        ),
        migrations.AddField(
            model_name='headunit',
            name='height_int',
            field=models.IntegerField(default=0, verbose_name='Приближенная высота'),
        ),
        migrations.AddField(
            model_name='headunit',
            name='width_int',
            field=models.IntegerField(default=0, verbose_name='Приближенная ширина'),
        ),
    ]
