# Generated by Django 5.1 on 2024-09-07 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moncalc', '0013_headunit_gu_diag_int_headunit_height_int_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Diagonal',
        ),
        migrations.DeleteModel(
            name='Horisontal',
        ),
        migrations.DeleteModel(
            name='Vertical',
        ),
        migrations.RemoveField(
            model_name='headunit',
            name='height_int',
        ),
        migrations.RemoveField(
            model_name='headunit',
            name='width_int',
        ),
    ]
